on:
  push:
    tags:
      - 'v*' # Срабатывает при создании тегов, начинающихся с "v" (например, v1.0.0)

# Выдаем права на создание релизов
permissions:
  contents: write

jobs:
  build:
    runs-on: windows-latest

    steps:
    # 1. Клонирование кода
    - name: Checkout code
      uses: actions/checkout@v4

    # 2. Настройка окружения MinGW
    - name: Setup MinGW
      uses: msys2/setup-msys2@v2
      with:
        msystem: UCRT64
        update: true
        install: mingw-w64-ucrt-x86_64-gcc

    # 3. Компиляция проекта
    - name: Build project
      shell: msys2 {0}
      run: |
        windres resources.rc -O coff -o resources.res
        g++ -o Art_RDP_Launcher.exe art_rdp_launcher.cpp resources.res \
          -lshell32 -lcomctl32 -luser32 -lgdi32 -municode -mwindows -std=c++17 \
          -static-libstdc++ -static-libgcc -Wl,--dynamicbase,--nxcompat,--high-entropy-va

    # 4. Создание релиза и прикрепление exe-файла
    - name: Create Release and Upload Asset
      if: startsWith(github.ref, 'refs/tags/')
      uses: softprops/action-gh-release@v2
      with:
        files: Art_RDP_Launcher.exe
        name: Release ${{ github.ref_name }}
        draft: false
        prerelease: false
        generate_release_notes: true # Автоматически сгенерирует список изменений из коммитов
